### ISSUE TITLE
Rename DB migrations on dev

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#10354]
There is a gap between 0055 and 0067 on dev for the DB migrations. These should be checked and renamed in order to avoid further issues when upgrading

**Comment by EVODelavega** [comment]
I believe the gap is between 0055 and 0068. After going through those migrations, while some can be combined to reduce the number of migrations to move, it's not really worth the extra effort. It'd be far easier to just move all migrations to 0069 and up, so we don't run in to broken migrations later on because of a typo cramming several migration steps into one.
