### ISSUE TITLE
[Bug]: balances API takes a very long time to run and should have defaults / mandatory fields

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#10904]
### Problem encountered

A user has reported that when running the following it does not return any values. In testing this does indeed return data but only after a very long time.

```
curl -L -X GET 'https://api.n00.testnet.vega.rocks/api/v2/balance/changes?filter.partyIds=5ca0f1a6811f234cba269b9c48b82a0bf9198107ab01364ff0c151329aaac866' \
-H 'Accept: application/json'
```

We need to investigate:

- what can be done to protect data nodes from falling over, if for instance a user runs this query with many partyIDs
- come up with sensible defaults / mandatory fields
- make the change 

### Observed behaviour

Very long running query

### Expected behaviour

Some default or protection to avoid queries that risk the data node falling over

### Steps to reproduce

```bash
1.
```

### Software version

0.75.0-preview.8

**Comment by guoguojin** [comment]
This is because the API does not properly enforce a date range causing the query to search through the entire history of account balances to filter for a single party.
If an appropriate start/end date is provided via the date range parameters, then the query will run much quicker. Alternatively, if a cursor is provided in the pagination object, then a date time filter will be available in the cursor.

Therefore, we will update the API to ensure that an appropriate date range or pagination cursor is provided in the request, and return an appropriate error if it is not. We will also update the documentation to highlight the requirements.

We will also add validation on the date range so that an inappropriate range will result in an error.
