### ISSUE TITLE
Decimal place mismatch on average entry price

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#5708]
```{
  "data": {
    "party": {
      "positions": [
        {
          "averageEntryPrice": "8000000",
          "market": {
            "decimalPlaces": 2,
            "data": {
              "markPrice": "8300"
            }
          }
        }
      ]
    }
  }
}
```

The mark price is correct (two decimal places on market so it's 83); the average entry price should also be 83 i.e. 8300.

**Comment by EVODelavega** [comment]
@davidsiska-vega this is going back in time a bit, but as I recall, the average entry price for a party would match the mark price after the MTM settlement was performed successfully. Not knowing anything more about this particular case, the average entry price might differ from the mark price in cases where traders ended up distressed, and parties were unable to receive their full settlement amount because of loss socialisation.

Then again, a few months ago, I vaguely recall removing a particular event because it seemed to double some values in the positions API, so perhaps the API's don't return the correct values because of this, or the events haven't been received/fully processed yet at the time where you got this response. Could you provide some more details on how to reproduce?

**Comment by davidsiska-vega** [comment]
@EVODelavega  I was not questioning the amounts (I think) merely the decimal places used. I thought average entry price should use the same number of decimals as the mark price.
