### ISSUE TITLE
New command/TX type for new validators to be requested to build signatures

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#5841]
In order to request that new validators build and submit their signature for the signature bundle we need to implement a new tx type / command to require the validators to do this.

- [ ] discuss the best approach and refine this ticket
- [ ] implement the functionallity
- [ ] update the docs (node operator instruictions)

This issue requires further discussions and refinement

Also to consider (and resolve) is the impact on:

- [ ] system tests
- [ ] vegacapsule

**Comment by jeremyletang** [comment]
As of now, signature to add / remove a validator are down like so:
- a node operator send the command to announce their intent to become a validator. As part of this command is their node ethereum address
- when a node is added to the validator set, signature to be used on the bridge are emitted. Each signature are made to be submitted by a specific ethereum wallet, the address is part of the message to be verified. Signatures are emitted to be submitted by the new validator using the addres they set in the announce node
- Similar process when a node is to be removed.

Now, that is not working much nicely, as that means that validators would need to reuse their node wallet, which is unpractical when using e.g: clef.

We discussed with the team, and propose to stop generating the signature when a node join/leave the validator set. But instead to add a new Command, so the network would issue on demand the signature.

Suggested payload:
```proto
message IssueSignatures {
    string submitter = 1;
    vega.NodeSignatureKind kind = 2; // ADD_SIGNER, REMOVE_SIGNER
    string validator_node_id = 3; // the node for which to emit the signatures.
}
```

Most of the implementation as it is now will be compatible with this (API, events, etc) we'll just need to stop creating and sending automatically the signatures when the validator set changes.

**Comment by davidsiska-vega** [comment]
I don't see any problem with this.

**Comment by MM0819** [comment]
So does this mean every current validator would need to execute this command to generate the bundle to be given to the joining or leaving validator? (or rather 2/3+1 of current validators)

**Comment by jeremyletang** [comment]
> So does this mean every current validator would need to execute this command to generate the bundle to be given to the joining or leaving validator? (or rather 2/3+1 of current validators)

Yez.

**Comment by MM0819** [comment]
Hmmm... So compared to now, where they don't have to do that manually, this will take much longer for them to do, and it will mean that it might take several days for a new validator to join the network. I guess we don't have much choice because, as you say, clef is not working with the automatically generated approach. 

However, do we see any other issues with having the validators effectively acting as gatekeepers of who gets to join the network (and leave)? The way I see it, they can effectively keep new candidates out if only 1/3 of them refuse to sign a change to the bridge. Whereas, when we automatically generate the signatures, it would require the validators to run a fork of the code to change this behaviour, which surely requires 2/3 of them to collude instead of 1/3. That means it takes much fewer validators to collude with this approach to prevent changes to the validator set.

Please tell me if I completely misunderstood how it works!

**Comment by MM0819** [comment]
> > So does this mean every current validator would need to execute this command to generate the bundle to be given to the joining or leaving validator? (or rather 2/3+1 of current validators)
> 
> Yez.

Hmmm... So compared to now, where they don't have to do that manually, this will take much longer for them to do, and it will mean that it might take several days for a new validator to join the network. I guess we don't have much choice because, as you say, clef is not working with the automatically generated approach.

However, do we see any other issues with having the validators effectively acting as gatekeepers of who gets to join the network (and leave)? The way I see it, they can effectively keep new candidates out if only 1/3 of them refuse to sign a change to the bridge. Whereas, when we automatically generate the signatures, it would require the validators to run a fork of the code to change this behaviour, which surely requires 2/3 of them to collude instead of 1/3. That means it takes much fewer validators to collude with this approach to prevent changes to the validator set.

Please tell me if I completely misunderstood how it works!

**Comment by wwestgarth** [comment]
> > So does this mean every current validator would need to execute this command to generate the bundle to be given to the joining or leaving validator? (or rather 2/3+1 of current validators)
> 
> Yez.

Thats not my understanding. I thought it would work like this:
- validator A is promoted to a Tendermint validator joins
- validator A wants to add themselves to the multisig contract so sends in a transaction with `(their ETH address, their nodeID of Val-A)` and they'll then be able to get from the data-node a full set of signatures that they can then submitter using their non-clef ETH key.
- validator B is demoted
- one of the Tendermint validators sends in a transaction with `(their ETH address, their nodeID of Val-B)` and they'll then be able to get from the data-node a full set of signatures that they can then submitter using their non-clef ETH key.
?

**Comment by jeremyletang** [comment]
> > > So does this mean every current validator would need to execute this command to generate the bundle to be given to the joining or leaving validator? (or rather 2/3+1 of current validators)
> > 
> > 
> > Yez.
> 
> Thats not my understanding. I thought it would work like this:
> 
>     * validator A is promoted to a Tendermint validator joins
> 
>     * validator A wants to add themselves to the multisig contract so sends in a transaction with `(their ETH address, the nodeID of Val-A)` and they'll then be able to get (eventually) from the data-node a full set of signatures that they can then submitter using their non-clef ETH key.
> 
>     * validator B is demoted
> 
>     * one of the Tendermint validators sends in a transaction with `(their ETH address, the nodeID of Val-B)` and they'll then be able to get from the data-node a full set of signatures that they can then submitter using their non-clef ETH key.
>       ?

Correct yea. Sorry I must have not understood @MM0819 message

**Comment by wwestgarth** [comment]
Thinking about it, the good thing with automatic signature generation is that it only emits signature-bundles for changes to the validator set that actually happened. And we'll lose that.

For example, could  a single Tendermint validator go rogue, and submit 12 transactions to get sig-bundles to remove all other nodes apart from themselves?

We could control this by checking that a request for signatures for an add/removal actually matches the validator set changes that actually happened in the last epoch. But then if no one asks for the sigs within the epoch are people stuck on the contract forever?

**Comment by jeremyletang** [comment]
> Thinking about it, the good thing with automatic signature generation is that it only emits signature-bundles for changes to the validator set that actually happened. And we'll lose that.
> 
> For example, could a single Tendermint validator go rogue and submit 12 transactions to get sig-bundles to remove all other nodes apart from themselves?
> 
> We could control this by checking that a request for signatures for an add/removal actually matches the validator set changes that actually happened in the last epoch. But then if no one asks for the sigs within the epoch are people stuck on the contract forever?

yes we will need to keep around the signature that needs to be sent to ethereum. But that should be sufficiently easy to do, as we also need to wait for the events saying that the signature have been used on ethereums.
