### ISSUE TITLE
GraphQL accounts subscription does not return all accounts in a list

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5881]
GraphQL accounts subscription does not return all accounts in a list. Instead it pushes accounts as single objects and it's inconsistent with the other subscriptions.

**Comment by pscott31** [comment]
Hi, so there are possibly two things we're talking about here.

So first of all by design all the subscription functions only publish _changes_ to individual entities. So for example I would not expect `ObserveAccounts` to give you a full list of all the accounts; it's only going to tell you when an account (e.g. its balance) is updated. To get the full current list there is a ListAccounts RPC call.

Most ObserveXXX return an update at a time:

```Accounts, Position, Candle, Votes, MarginLevels, Rewards, Governance, Delegations, TransferResponse```

One message per update is a pretty natural way of doing things but I think for performance reasons to eliminate some grpc overhead for messages that are very frequent we decided to batch a bunch of changes into a single message. The only ones that do this are

```[Orders, Trades, MarketDepth, BusEvents]```

The downside to batching is that you add on a little bit of latency (e.g. depth is sent out every 100ms, orders at the end of a block)

So I think it's appropriate to do it differently for different events. I wouldn't call this a bug. 

I'll leave the issue open for a few days to give chance for a bit of discussion if you feel the API should work in a different way.

**Comment by MM0819** [comment]
> Hi, so there are possibly two things we're talking about here.
> 
> So first of all by design all the subscription functions only publish _changes_ to individual entities. So for example I would not expect `ObserveAccounts` to give you a full list of all the accounts; it's only going to tell you when an account (e.g. its balance) is updated. To get the full current list there is a ListAccounts RPC call.
> 
> Most ObserveXXX return an update at a time:
> 
> `Accounts, Position, Candle, Votes, MarginLevels, Rewards, Governance, Delegations, TransferResponse`
> 
> One message per update is a pretty natural way of doing things but I think for performance reasons to eliminate some grpc overhead for messages that are very frequent we decided to batch a bunch of changes into a single message. The only ones that do this are
> 
> `[Orders, Trades, MarketDepth, BusEvents]`
> 
> The downside to batching is that you add on a little bit of latency (e.g. depth is sent out every 100ms, orders at the end of a block)
> 
> So I think it's appropriate to do it differently for different events. I wouldn't call this a bug.
> 
> I'll leave the issue open for a few days to give chance for a bit of discussion if you feel the API should work in a different way.

@pscott31 well, the issue here is that I'll have multiple accounts for a single settlement asset. For example, I will have a general account and a margin account. The margin account can't change without the general account changing, too. 

E.g. if more margin is required to cover my positions, it will be credited to the margin account and debited from somewhere else (the general account, I think?). So, by not returning a list, it means that for some time, my local state will be out of sync with the core as there will be some latency between receiving the updates about each account.

This might seem pedantic, and you may say that I shouldn't worry because I'll get the updates more or less sequentially anyway. However, from the perspective of a client subscribing to these messages, it's not intuitive to receive separate messages for updates that are intrinsically connected in some way. 

As for receiving "all accounts", I have created a separate issue about the fact that the current state is not sent to the client upon opening a new connection. I think if that issue is addressed, then the idea of only sending updates when something changes is perfectly fine, as long as all relevant updates are broadcasted in a single message.

**Comment by pscott31** [comment]
OK I understand, I'll make make account balance updates batched up per block
