### ISSUE TITLE
Reference IDs in API responses are not useful

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5882]
Returning reference IDs for linked objects in the REST API is kind of useless to the user. For example, in this endpoint, I can't do much with the hexadecimal asset ID (https://n06.testnet.vega.xyz/datanode/rest/parties/6817f2b4d9464716c6756d2827d893872b1d33839e211c27a650629e428dc35c/accounts). It would be much better to return the asset object, so I have direct access to the information I need.

Obviously this limitation can be worked around, but it significantly increases the development overhead of integrating with Vega.

**Comment by barnabee** [comment]
Don't really understand this. Doesn't seem like good practice to follow every database join and embed objects… how far should this go?

In a centralised exchange you can probably make the ID human readable like "BTC" but that's not really possible on chain. If you want to follow the joins you can use a GraphQL query instead of REST anyway.
