### ISSUE TITLE
Amend order: should provide the new size not delta

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5889]
Passing a delta to the amendment API is inconsistent with how other exchanges work and complicates the handling on the client

**Comment by jeremyletang** [comment]
This is implemented as per specficiation if not mistaken, feel free to open a ticket there first then.

**Comment by barnabee** [comment]
@MM0819 

The design is as such because an amend is non-deterministic if you specify a new total quantity, because you don't know how much more of your order will trade before your txn is processed. On a centralised exchange there may be only a few microseconds for that to happen so probability that you end up trading twice as much as you wanted to might be low (but non-zero!) but on Vega there will be several seconds.

By calculating the delta from the quantity you _think_ the order has left to the quantity you want and sending that, you know that the amendment will have the same effect as if you'd changed the quantity before any other trades ocurred (unless you're reducing and too much trades in which case some extra may still get traded). The range of outcomes is more predictable and I would argue close to what you intended.

If you really want the other behaviour you can batch a cancel and a submit together. I guess in future we could investigate supporting either a delta or a new quantity on amends but I can't see why we'd prioritise this now.

**Comment by jeremyletang** [comment]
Removed bug label as this is per specs and could be suggest to improvement in the future.

**Comment by barnabee** [comment]
Further discussion should be in the specs repo / protocol design channel on Slack.
