### ISSUE TITLE
Eth key rotation - Cannot remove old ethereum key from Multisig (remove_signer fails to return successful status)

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6075]
Test test_ethereum_key_rotation - failure can be see by running this test

After ethereum key rotation occurs and confirms via an event the test adds the new eth key to the MS contract and then removes the old key from the MS contract.

In both add and remove signer trx, the submitter/account is the ganache main eth address and private key.

Adding the key to the contract works ok and status is 1 and is_valid_signer function returns True. Event confirms.
Remove signer step fails to confirm ok on the contract.
-- GetERC20MultiSigSignerRemovedBundlesRequest used to return signature bundle and nonce
-- trx submitted to add enough eth to perform removal trx with gas
```
        transaction = self._multisig.functions.remove_signer(
            old_signer,
            int(nonce),
            bytes.fromhex(signatures)).buildTransaction({
            'gas': 1000000,
            'gasPrice': 0,
            'from': account.address,
            'nonce': w3.eth.getTransactionCount(account.address)
        })
        self._send_raw_transaction(account, transaction)
```

Trx fails
old_signer is original validator ethereum address
nonce and signatures is taken from API GetERC20MultiSigSignerRemovedBundlesRequest

Tried removing fist before adding signer but witnessed same failed status.

**Comment by wwestgarth** [comment]
So the problem here was an artefact of us using a small network with only 2 validator nodes and so we only have 2 keys on the contract. Trying to swap one by fist adding the new one, and then removing the old one, caused problems with us being able to exceed the threshold because we only have two sigs, but end up in a state with three keys on the contract.

I've pushed a change to the test branch with a good explanation: https://github.com/vegaprotocol/system-tests/pull/1015/commits/32136c99fa32e3e69ebe47d1eb2fa7ec6f6d1fbe

The test now passes: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/5383/pipeline/269
