### ISSUE TITLE
Validators without clef wallets fail to start after checkpoint restore when clef used by other validators

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6291]
test test_ethereum_key_rotation / branch feat_clef_ethereum_key_rotation

Steps to reproduce

- Setup network with 5 validators and two clef wallets on nodes 3/4 (test uses capsule_config_network_infra.hcl)
- Perform eth key rotation
- confirm events/multisig updates/datanode has new key for node
- Produce checkpoint
- Restore from checkpoint
- All nodes are restored apart from validator 1
logs 2022-09-23T17:36:32.657+0100	INFO	root	node/node.go:95	starting vega	{"version": "v0.56.0+dev", "commit-hash": "a7ce1fa22b1bd301753367e4798141c6ffc7ecb0-modified"}
- Validator 1 fails - stderr - couldn't get node wallets: failed to dial Clef daemon: dial unix: missing address

jenkins run demonstrating
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/10461/pipeline/293

**Comment by wwestgarth** [comment]
Are you rotating from a non-clef key to a clef key? I think the issue is because after rotating to a clef key, the node's config file is still for a non-clef key and so when we restart from a checkpoint we have a clef nodewallet but the clef address is not set. On the clef nodes it looks like this: https://github.com/vegaprotocol/system-tests/blob/develop/vegacapsule/vega_validator_clef.tmpl#L106

**Comment by vega-paul** [comment]
@wwestgarth Thank for the info but Im confused - can you walk me through what updating the nodes config entails. I was determined to let rotation and restore take care of everything.

**Comment by wwestgarth** [comment]
Ok, im back to it being a possibly being a bug! Core should probably be using the clef address saved in the registry and not the config file here: https://github.com/vegaprotocol/vega/blob/develop/core/nodewallets/ethereum_handler.go#L56
