### ISSUE TITLE
Do not show hidden files nor directories as wallet

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/vega#6358]
# Software information
Build info:
- Version: v0.2.1

Installation:
- [x] I downloaded it from the GitHub releases page.

# Problem encountered
Opened wallet folder to delete wallets in /Library/Application Support/vega/wallets
.DS_Store file gets automatically created
File is now shown as wallet in the wallet app

<img width="460" alt="Screenshot 2022-09-16 at 11 14 50" src="https://user-images.githubusercontent.com/30622993/190617981-035acea7-bd45-42a9-8520-d6325a1a0f63.png">

# Expected behaviour
.DS_Store file should not be shown as wallet in the wallet app

**Comment by ValentinTrinque** [comment]
The fix could be to ignore hidden files when reading the file system.

Also it's important to not that it's impossible today to know if a file is a proper wallet or not, since those files are encrypted and thus it's impossible to know what's inside.

So we can have a list of common files to ignored, plus, certain rules, but that's it, for now.
