### ISSUE TITLE
Reducing market.liquidity.minimum.probabilityOfTrading.lpOrders param has no effect on existing placed LPs on book

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6861]
This AC Under test

Change of the network parameter market.liquidity.minimum.probabilityOfTrading.lpOrders will immediately change the minimum probability of trading which affects placement of LP orders. If the parameter has been decreased then any LP order volume that may have been pushed "in" due to the price level having probability of trading smaller than the former value may now be placed at the price level specified by the LP order. If the parameter has been increased then LP order volume that may have been placed at price levels that have lower probability of trading than this value will now be placed at the price corresponding to the new probability of trading. ([0038-OLIQ-007](https://github.com/vegaprotocol/specs/blob/master/protocol/0038-OLIQ-liquidity_provision_order_type.md#0038-OLIQ-007))

What we see is that when LP is placed on the book at a wide offset, when changing the param market.liquidity.minimum.probabilityOfTrading.lpOrders from 0.01 to 0.1 -nothing happens to the placed LPs. There is no repricing of the existing LPs. 

We were expecting to see that the volume from the LP order has been pushed even further in (closer to best bid / ask) when reducing this parameter.

**Comment by ze97286** [comment]
the expectation sounds wrong to me @witgaw. The probabilityOfTrading comes into play in a number of different conditions:
1. if the given price for which we calculate probability of trading is <minPrice or > maxPrice
2. there's no consensus yet on probability of trading
3. if the probability get from the offset table is lower than this min

in all other cases making it lower or higher won't matter. In fact, to demonstrate that it works as expected you can make it > 0.5. then it will be used rather than the probability you get from the offsets calculation.

**Comment by davidsiska-vega** [comment]
@vega-paul Does nothing still happen if you update one of the orders that the LP volume is pegged to? This may force the update to happen.

**Comment by witgaw** [comment]
I'll put a feature test that tests it now, should be easier to know what's going on and then reproduce it as a system test
