### ISSUE TITLE
Error received during starting datanode - terminating connection due to administrator command

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7006]
Running against the below branches:

vega - dehistory-failed-to-get-analysis
vegacapsule - add-swarm-key-support
systemtests - fix_datanpode_swarmkey_config

Jenkins Run:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31720/

Error Received:

`failed to flush subscriber:flushing ledger: failed to copy ledger entries into database:FATAL: terminating connection due to administrator command (SQLSTATE 57P01)`

Jenkins Error Link:

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31720/artifact/testnet/logs/testnet-nodeset-full-3-full/data-node-3.stderr-2022-12-01T13%3A39%3A41Z.log/*view*/

**Comment by wwestgarth** [comment]
This all happens after the tests have finished with the datanode chugging along for a good 10 seconds afterwards. 

The error:
```
terminating connection due to administrator command (SQLSTATE 57P01)
```
just means "postgres is shutting down so its cancelling your stuff" and vegacapsule doesn't do anything special when you stop the network, it just kills all the processes in parallel. So I reckon here the error is just because on this occasion it just so happened that postgres got stopped before the datanode at a time where the datanode was trying to do something. Which is fine because, we're killing everything, it doesn't matter. We just want it all gone.
