### ISSUE TITLE
[ALERT] deHistory Segment ID differ from the others

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7226]
from:

- https://github.com/vegaprotocol/incidents/issues/7864

We are seeing on all environments that deHistory Segment ID differ from the others. 

The above issue contains information of the issue alerted. This needs to be investigated, fixed and tests written to pick this issue up during development.

The incidents repo also contains other instances of this issue on other networks.

**Comment by ettec** [comment]
Testnet is in sync.    Stagnet3 out of sync is because it was upgraded via protocol upgrade process, therefore the database was not cleaned which means the bug in the event output from the previous release was still impacting the segment ids.  Secondarily, because the protocol upgrade process is not yet doing schema migration, this required the nodes be emptied and loaded from dehistory to get the schema's up to date.   Going forward we will now need to correctly handle schema migration.
