### ISSUE TITLE
positionsConnection filters

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#7289]
# Feature Overview

**In order to** show all positions across multiple keys
**We will** update the positionsConnection query
**So that** we can pass multiple partyId variables to the query

# Acceptance Criteria
- It is possible to filter by one or more partyIds
- It is possible to filter by one or more marketIds

# Additional Details

Ideally this would end up looking something like the AccountFilter

Its likely that we will also need to:
- Un-nest the positionsConnection field from under the party field, making it a top level query
- Deprecate `party.positionsConnection`

# Examples
```
input PositionFilter {
  partyIds: [ID!]
  marketIds: [ID!]
}

Query {
  positionsConnection(
    filter: PositionFilter,
    pagination: 
  ): PositionConnection
}
```

**Comment by guoguojin** [comment]
The current gRPC API that is used to retrieve the information for the positions connection currently only supports filtering by a single party and/or market id. To support multiple we have a number of options, one of which would result in a breaking change to the gRPC API.

1. Update the existing gRPC API to support multiple party/market in the request *BREAKING CHANGE*
2. Only support multiple party/market in the GraphQL API and make multiple requests to gRPC to fulfil the request (Horrible, not recommended)
3. Deprecate but don't change the existing ListPositions endpoint, and add a new ListPositions endpoint to the gRPC API that will support filtering by multiple party and/or markets, and set up the GraphQL API to use that endpoint instead of the old one.

I think 3 is probably the best option seeing as we're close to Go Live and we don't want to introduce breaking changes at this point.
