### ISSUE TITLE
Custom headers exposed by datanode returning incorrect data for connection status

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7385]
**Spec Ref:** 
https://github.com/vegaprotocol/specs/blob/master/protocol/0076-DANO-data-node.md

**AC:**
The DataNode must provide its current block height and connection status on responses to client requests so the client can determine whether or not the data is stale. ([0076-DANO-021](https://github.com/vegaprotocol/specs/blob/master/protocol/0076-DANO-data-node.md#0076-DANO-021))

Tried to test the above , however the custom header returned back is incorrect.

**Expected Result:**
Expect the below header to return status `CONNECTED` 

**Observed Result:**
Status returned is `DISCONNECTED`

**Full List of headers returned:**

`('Content-Type': 'application/json', 'Content-Type': 'application/grpc', 'Grpc-Metadata-X-Block-Height': '705', 'Grpc-Metadata-X-Block-Timestamp': '1674144788974243000', 'Grpc-Metadata-X-Vega-Connection': 'DISCONNECTED', 'Vary': 'Origin', 'Warning': '199 - "The headers [\'Grpc-Metadata-X-Vega-Connection\', \'Grpc-Metadata-X-Block-Height, \'Grpc-Metadata-X-Block-Timestamp\'] are deprecated and will be removed in a future version. Use their non-grpc-metadata prefixed counterparts instead."', 'X-Block-Height': '705', 'X-Block-Timestamp': '1674144788974243000', 'X-Vega-Connection': 'DISCONNECTED', 'Date': 'Thu, 19 Jan 2023 16:13:29 GMT', 'Content-Length': '317')`

**Jenkins Run:** 
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/43401/
**Jenkins Logs:** 
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/43401/consoleText  
**Jenkins Test Result:** 
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/43401/testReport/junit/tests.datanode/datanode_test/test_datanode_disconnection/

System Tests Branch: **feat_expose_custom_headers_datanode**
System Tests Marker: **datanode_disconnection**

**Comment by fkondej** [comment]
Just so you know, I have been checking those headers for the past few days on our environments: Devnet, Stagnet 1, Stagnet 3 and Fairground. On every occasion, I saw the `x-vega-connection: CONNECTED` working.

You must have experienced an edge case where you hit `'X-Vega-Connection': 'DISCONNECTED'`. It would be good to understand better the conditions under which you get these results. Maybe it can be reproduced by whoever is going to look into this one.

**Comment by zale144** [comment]
@vegaprotocol/core OK, so the logic behind `DISCONNECTED` is coming from a check on the grpc conn `grpc.GetState() != Ready`. In the case reported in this issue, the `DISCONNECTED` value is because `state` is `Idle`. This is the default state when the connection channel is idle, meaning if there is no traffic between the server and the client, the gRPC connection switches to the `idle` mode in order to release unused resources. It is also the default initial state after calling `grpc.Dial`. This does not mean that the server is(n't) listening.

So, in order to "wake up" the connection channel and verify its state, we can:
- Call `Invoke` on any method, such as `Statistics`. But I see some overhead here, since this would be executed on every request to the data-node gRPC server, and with GraphQL, I believe there will be quite a few
- Call `conn.Connect()` before checking the state (this is asynchronous, so the state might not be updated on time)
- Right now, the `x-vega-block-height` header is coming from the `BlockService` which is basically the last recorded block height in the data-node database. We could instead call the `CoreService` and get the last block height directly and at the same time verify that the core is awake and connected. Again, here we will have some overhead, and also the last block in the core might be more fresh than the one recorded in the data-node database.
- Make do with just the last block height and get rid of the `x-vega-connection` header. I wasn't really convinced in the first place that the connection status will be a reliable way to determine whether data-node is behind and is serving stale data. Isn't it possible that the data-node can return `CONNECTED` while still serving stale data? We can only know that it's (dis)connected *right now*.

**Comment by zale144** [comment]
@jeremyletang ☝️
