### ISSUE TITLE
Paginate historic rewards data

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega#7609]
# Task Overview

As a Governance dapp user
I want to see a paginated list rewards (by epoch)
So that I can browse rewards information without the page taking forever to load / falling over due to the volume of data

# Acceptance Criteria
We will know when this technical task is complete when the Governance dapp team are able to query the graphql api and return data in a way that allows us to:

- View a user's epoch's rewards
- Specify how many epochs of data to display
- Understand how many pages of data are available to view

## Background
You guys recently very kindly enabled us to filter rewards data per epoch #6650, which is really super and we are working on implementing this feature in the frontend. However, we also need to be able to paginate this data effectively to provide a good user experience. 

# Test Scenarios (TBC)
Detailed scenarios (1-3!) that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) 
See [here](https://github.com/vegaprotocol/vega/tree/develop/integration/) for more format information and examples.

# Dependencies (TBC)
Links to any tickets that have a dependent relationship with this task.

# Additional Details (optional)
Any additional information including known dependencies, impacted components.

# Examples (optional)
Code snippets, API calls that could be used on dependent tasks.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by pscott31** [comment]
Hi ho,

I think I must not be grokking something about what you want to do here - the rewards connection on a party is already paginated:

![image](https://user-images.githubusercontent.com/94362991/220167512-5eda246b-269e-48ce-bdd3-30c3bc081d19.png)

**Comment by pennyandrews** [comment]
@dexturr @sam-keen @ckpringle can we pick this up in standup in the morning and get to the bottom of this? Thanks

**Comment by pscott31** [comment]
Looking a bit harder at the ticket:

- View a user's epoch's rewards
Yes, we can

- Specify how many epochs of data to display
We can, by specifying `fromEpoch`, `toEpoch` but maybe that isn't the most useful way for you to specify it? Would you rather maybe `lastEpochs` or something to show you the last _n_ epochs?
  
- Understand how many pages of data are available to view
You **can't** currently do this without fetching all the pages. I'm pushing back a little bit on this one not because I'm being difficult, but it's tied a bit to how we have designed our general purpose paging mechanism. 

In general it can be quite expensive to calculate how many rows are in the result set of a query; figuring out the exact same number is very nearly as hard for the database as simply getting all of them.

That's why we've carefully designed all the cursors and whatnot so the database should never have to look all the way back to the start of the chain to answer any question particular question; it can 'return early' once it has enough to fit in a page - and the cursor passed in means it can quickly figure out where to carry on when getting the next page.

For example, asking how many orders there are in total when the number gets to a few 10's of millions can take quite some seconds.

A downside to this is that you only know you've gotten to the end when you get to the end - and you can't 'skip' to the middle of a dataset, you must fetch a page at a time like you can with limit/offset pagination.

Now it may well be that rewards table is a small enough table that this isn't a practical issue; but right now we have the nice property that all our pagination follows the same pattern, and I am somewhat averse to mixing paradigms unless there's a really good reason to.

I guess the bit of the puzzle that I am missing is figuring out what it is that you can't currently do that you would like to be able to. Perhaps a quick call is in order.

**Comment by pscott31** [comment]
OK had a chat with @dexturr and front end are happy as-is for now:

> So i think we are basically just going to go with a next/back button based on hasNextpage
> I think the main thing is jumping to the middle of the list in some cases and an assumption of standard pagination was present
> But as you say if we need epoch 17-1000 we can just request that as a filter rather than pagintation
> Which satisfies the needs :smile:

So I'm going to close the issue, we can revisit later if needed.
