### ISSUE TITLE
Forgot wallet passphrase (reset passphrase)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega#7623]
It should be possible to reset the passphrase of a wallet when providing the recovery phrase.

E.g. https://metamask.zendesk.com/hc/en-us/articles/360039616872

**Comment by ValentinTrinque** [comment]
Unfortunately this is not possible with the way to encrypt the file, as there is no way to retrieve any data from the wallet file without the passphrase.

In order to support this we will have to rethink the file structure.
1. we need the hash of a cryptographic node derived from the recovery phrase. That will allow us to assert whether or not a recovery phrase  generated the wallet.
2. Instead of encrypting using the user passphrase, we need to introduce an intermediary decryption key to encrypt the wallet data. So whatever the user passphrase is, if we have that key, we can decrypt the wallet data. That decryption key can't be changed, because it has to be deterministic. It will probably be derived from the cryptographic node mentioned above.
3. We will then use the user passphrase to encrypt the decryption key.

**Proof of concept for the file:**
```js
{
   "fileVersion": 2,
   "walletFingerprint": "<the hash of a cryptographic node derived from the recovery phrase, so we can identify the wallet using a seed phrase>".
   "encryptedDecryptionKey": "<the encryption key, encrypted using the user passphrase>",
   "wallet": "<the data of the wallet with keys, metadata and all, encrypted using a decryption key>"

}
```

**Proof of concept for a regular decryption process:**
```go
content := FileContent{}

readFile(fileBytes, &content)

encryptionKey := crypto.Decrypt(content.EncryptedDecryptionKey, userPassphrase)
walletBytes := crypto.Decrypt(content.Wallet, encryptionKey)

wallet := Wallet{}
if err := json.Unmarshall(walletBytes, &wallet); err != nil {
   // ERROR: Invalid user passphrase, or corrupt file
}

return wallet
```

**Proof of concept for a passphrase reset:**
```go
content := FileContent{}

readFile(fileBytes, &content)

derivedWallet := deriveWallet(userRecoveryPhrase)

if derivedWallet.Fingerprint != content.walletFingerprint {
  // ERROR: The recovery phrase specified by the user is not the same as the wallet.
}

walletBytes := crypto.Decrypt(content.Wallet, derivedWallet.EncryptionKey)

wallet := Wallet{}
if err := json.Unmarshall(walletBytes, &wallet); err != nil {
   // ERROR: the decryption key is not the right one.
}

saveWallet(wallet, newUserPassphrase)
```
