### ISSUE TITLE
Client Interation - wallet does not submit the excess transactions with a PoW of higher difficulty

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7651]
This AC
```
The new parameter is communicated to and adapted/used by the wallet, i.e., if a user has too many transactions according to the new parameter, AND if the parameter spam.pow.increaseDifficulty is set to 1, the wallet submits the excess transactions by submitting a PoW of higher difficulty. ([0011-NP-CLIE-002](https://github.com/vegaprotocol/specs/blob/master/non-protocol-specs/0011-NP-CLIE-client-interaction-tests.md#0011-NP-CLIE-002))
```

Test (test_spam_pow_wallet_submits_excess_with_higher_pow_difficulty) fails as follows:

20 trx are submitted (max=3, increase_difficulty=1)
block heights and pow difficulty for each trx is captured after processing
We build a register of (block heights, pow_diff) for each trx submitted as follows:
We take the (max) first trxs and obtain highest difficulty) - max_trx_set
We take the rest of the trxs and obtain the lowest difficulty) - excess_trxs
We expect the wallet to submit the excess transactions by submitting a PoW of higher difficulty after the max has been reached (excess) - this is not happening

max_trx_set=[(5617, 4), (5617, 4), (5617, 6)]
excess_trxs=[(5617, 6), (5617, 6), (5617, 6), (5617, 6), (5618, 6), (5617, 7), (5617, 7), (5617, 7), (5619, 7), (5617, 8), (5617, 8), (5618, 8), (5618, 8), (5618, 8), (5617, 9)]

**Comment by vega-paul** [comment]
Submitted 6 trxs async
[bock height, difficulty, tied_block]
max trx = 3

[(9213, 4, ‘9211’), (9213, 7, ‘9211’), (9213, 6, ‘9211’), (9213, 6, ‘9211’), (9213, 8, ‘9211’), (9213, 4, ‘9211’)]

expected the wallet logic to increment the 4th trx difficulty

**Comment by ze97286** [comment]
from the core point of view, this set is perfectly fine, in that the total difficulty of it is a lot more than is needed and no transaction has difficulty less than 4. From a wallet point of view, I doubt this is this above is the order in which they are hitting the wallet. I would imagine both txs with difficulty 4 are hitting the wallet first and then the rest of them in a random order because after seeing 3 txs, the wallet will increase the minimum difficulty by 1. But just to be clear, I don't understand what you're doing in your calculation above with the maximum difficulty observer in a set of n transactions. This has no meaning. The pow must be with difficulty >= the desired one, but it can be a lot greater. When we increase difficulty, it just means we expect the difficulty to be +1 from the base, not from the maximum observed difficulty in the preceding batch attached to the same block.

**Comment by vega-paul** [comment]
The above list reflects the exact order submitted and the difficulty returned)

The req states that the excess trxs - in this case 4 through 6, should be sent with a higher difficulty that the preceeding trx and we can see that is not happening.

The new parameter is communicated to and adapted/used by the wallet, i.e., if a user has too many transactions according to the new parameter, AND if the parameter spam.pow.increaseDifficulty is set to 1, the wallet submits the excess transactions by submitting a PoW of higher difficulty. ([0011-NP-CLIE-002](https://github.com/vegaprotocol/specs/blob/master/non-protocol-specs/0011-NP-CLIE-client-interaction-tests.md#0011-NP-CLIE-002))

**Comment by ze97286** [comment]
>The req states that the excess trxs - in this case 4 through 6, should be sent with a higher difficulty that the preceeding trx and we can see that is not happening.

no, it doesn't say that and is clearly incorrect. what it does say is that it must be at least base_difficulty + i*batches, so the first batch require base difficulty, the second batch will require base difficulty + 1, etc. 

> The above list reflects the exact order submitted and the difficulty returned). The pow difficulty is calculated at transaction level using the block the trx is tied to.

I'd like to see evidence that these six transactions were sent in that order. I don't believe any of the second batch of 3 transactions _can_ have difficulty less than 5 with the code in the wallet.
