### ISSUE TITLE
Wallet difficulty not set correctly for excess trx in same block/tied block

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7716]
Evidence here
[https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/55115/testReport/junit[…]spam_pow_wallet_submits_excess_with_higher_pow_difficulty/](https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/55115/testReport/junit/tests.spam/spam_client_interaction_test/test_spam_pow_wallet_submits_excess_with_higher_pow_difficulty/)

Submitting 4 trx with a max trx of 2 per block
base_pow_diff is 4 and pow_increase_diff is 1

We see 4 trx in same block and all tied to same block

difficulties expected to increase for the excess trx in same block but we see something else

These are generated results from trx upto the max (2)
[block, diff, tied_block]
[(549, 5, '547'), (549, 4, '547')]

These are generated results from excess trx after the max (2)
[(549, 5, '547'), (549, 4, '547')]

All tied to same block so Im expecting an increase in diff for the 2nd set.

Test is failing because wallet uses a difficulty of 5 and 4 in the excess trx , which is same as the first two trx. But there should be an increase on both excess trx above base diff of 4.

Can you explain why Im seeing these difficulties settings?

**Comment by wwestgarth** [comment]
There is no core bug here, its just a timing issue in the system-test in these lines:
```
set_spam_pow_numberofTxPerBlock(2)
to_send = 4
max_trxs = 2
height_register, hash_responses, wallet_warnings, _ = submit_trxs(
    number_trxs_to_send=to_send, max_trx=max_trxs, async_trx=False
)
```

When `numberofTxPerBlock` is changed the new value takes affect for all pow tied to the block the proposal was enacted in +1. It just so happens that _sometimes_ the enacted-event is seen by the test code, and it moves on to `submit_trxs()` before the block height has ticked on. This means the wallet momentarily ties all its proof-of-works to a block with the old network-parameter-value.

Here is an example: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/55420/pipeline

The wallet has sent 4 transaction with pow tied to block 547:
```
max_trx_set=[(549, 5, '547'), (549, 4, '547')]
excess_trxs=[(549, 5, '547'), (549, 4, '547')]
```

We can see that the network parameter that sets `spam.pow.numberOfTxPerBlock` to `2` is enacted also in block 547:
```
{"id":"547-6","block":"DE4DD2E3E9CD5E2CFF8F9B91940D2DD4181A61EF0F783261A819712F2BD4269C","type":"BUS_EVENT_TYPE_PROPOSAL","proposal":{"id":"9224e59c75901449d8dd7d5273347bb7211f958e4b5aa361272d3ed4176a7638","reference":"9823037834","partyId":"37005767ccbc21cebaadf765bec43f2ad3f98fafd464920162ec026188d172d4","state":"STATE_ENACTED","timestamp":"1677596797475348144","terms":{"closingTimestamp":"1677596809","enactmentTimestamp":"1677596811","updateNetworkParameter":{"changes":{"key":"spam.pow.numberOfTxPerBlock","value":"2"}}},"rationale":{"description":"Update network parameter","title":"Network Param Update: spam.pow.numberOfTxPerBlock"},"requiredParticipation":"0.00000015","requiredMajority":"0.66"},"version":1,"chainId":"testnet-001","txHash":"DE4DD2E3E9CD5E2CFF8F9B91940D2DD4181A61EF0F783261A819712F2BD4269C"}
```
and so the new `spam.pow.numberOfTxPerBlock` takes affect in block `548`. Because the wallet is using block `547` for its proof-of-work it is using `spam.pow.numberOfTxPerBlock=10` and correctly not increasing the difficulty.

How to make the test more stable?
The wallet pings a core endpoint to get the proof-of-work information for the latest block: https://github.com/vegaprotocol/vega/blob/develop/protos/sources/vega/api/v1/core.proto#L72

It would make sense for the system-test code to ping this endpoint after changing the network parameter values and waiting until the [pow-block-state](https://github.com/vegaprotocol/vega/blob/develop/protos/sources/vega/api/v1/core.proto#L398) for a block-height bigger than when the proposal was enacted appears, and the correct new values are present.

**Comment by wwestgarth** [comment]
Actually why is it enacted-block + 1. 

If the proposal is enacted in block N, then we can safely update the pow parameter for that block because its not been commited i.e no one can have any pow against that block yet.

And also the spec says:
```
If there is a governance vote on parameter changes taking effect at block height h, then the parameter is valid for all PoWs that are tied to a block of height h or later
```
