### ISSUE TITLE
Excessive delay to update normalisedScore on datanode

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7762]
Normalised Score check fails to find 0.5 inside 20 or so epochs (epoch is 5s). Intermittent failure, time to find expected score has exceeded generous timeouts.

Evidence
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/55953/testReport/junit/tests.validators/rewards_split_test/test_ersatz_reward_split/

Network has 5 nodes, 3 TM and 2 Ersatz
Ersatz start with 500 tokens TMs starts with 1000

We remove two TM nodes

First ersatz delegation here
```
First delegation of 500000000000000000000 here
{"id":"216-3","block":"F9693D8648A5709095CACDD225B609635E5A4C39629BCD0B4533F428CDB3EC8C","type":"BUS_EVENT_TYPE_DELEGATION_BALANCE","delegationBalance":{"party":"3dac1ed95098027147ca2a916a5376bd9068a45f86fc0062b1f43fecdda50335","nodeId":"32576b55ee856dcae02a1657e8edf98d6df4ac71ec3551b43c4f2e35ccb71165","amount":"500000000000000000000","epochSeq":"25"},"version":1,"chainId":"testnet-001","txHash":"96EA45ED537462288DF759CE169DC3C2D3E6C3652ECB089CA80F23AB9ED76718"}
```

Expecting normalisedScore to be 0.5 
But the first block we saw 0.5 was 766, 550 blocks later...we use epoch API to get the scores.
```
{"id":"766-8","block":"FCC499413CDC18F95DADFCDB4D685B8864A4AFF2651CA041819F959001428F0C","type":"BUS_EVENT_TYPE_VALIDATOR_SCORE","validatorScore":{"nodeId":"6c1024fa171561957bf7ebcba36b71603b7f19f4dccb17feaf9d9c8940963762","epochSeq":"84","validatorScore":"0.5","normalisedScore":"0.5","validatorPerformance":"1","rawValidatorScore":"0.5","validatorStatus":"ersatz","multisigScore":"1"},"version":1,"chainId":"testnet-001","txHash":"FCC499413CDC18F95DADFCDB4D685B8864A4AFF2651CA041819F959001428F0C"}
# ```

**Comment by wwestgarth** [comment]
The problem here is that the test requires that the ersatz validators have an equal performance score. Unfortunately the test is the first one run in the set, and because the network is new their performance scores are still rising from 0 as heartbeats are sent in.

When the test works the two ersatz happen to have an equal perf-score and stake score so that the split is 50/50, but sometimes depending on how the epoch’s lie against the heartbeats they’ll have the same stake score but different perf scores. In the case linked one has 0.9 the other 1. If they both had 0.9 it would pass, if they both had 1 it would pass.
So there isn’t a core issue here, we just need the test to be more resilient to this, either by waiting for a time when then perf scores are equal (the upper limit being both nodes having a perf score of 1) or change the test to calculate the split based on the performance score and not expect a 50/50 split always.
