### ISSUE TITLE
Data node is not able to start from fresh state

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7983]
# Problem encountered
One of the validator(v0.68.5) is getting this error:

```
Mar 25 19:35:41 Vega1 visor[4057]: 2023-03-25T19:35:41.275+0100        DEBUG        visor        visor/visor.go:165        failed to get upgrade status from API        {"error": "failed to call protocolupgrade.UpgradeStatus method: failed to post data \"{\\\"method\\\":\\\"protocolupgrade.UpgradeStatus\\\",\\\"params\\\":[null],\\\"id\\\":3667690688976448817}\": Post \"http://unix/rpc\": dial unix /tmp/vega.sock: connect: no such file or directory"}
...
Mar 25 19:35:42 Vega1 visor[4057]: 2023-03-25T19:35:42.480+0100        DEBUG        visor        visor/binaries_runner.go:103        Killing binary        {"binaryPath": "/usr/bin/vega"}
Mar 25 19:35:42 Vega1 visor[4057]: 2023-03-25T19:35:42.497+0100        ERROR        visor        visor/visor.go:137        Binaries executions has failed        {"error": "failed to prepare args for Vega binary: failed to get latest history segment from data node: failed to execute binary /usr/bin/vega [datanode network-history latest-history-segment --output json] with error: , {\"error\":\"no history segments found\"}\n: exit status 1"}
Mar 25 19:35:42 Vega1 visor[4057]: Error: maximum number of possible restarts has been reached: failed to prepare args for Vega binary: failed to get latest history segment from data node: failed to execute binary /usr/bin/vega [datanode network-history latest-history-segment --output json] with error: , {"error":"no history segments found"}
Mar 25 19:35:42 Vega1 visor[4057]: : exit status 1
```

More logs here: 
![image](https://user-images.githubusercontent.com/1239637/227911808-0d94c897-c433-40fa-aa00-65a91285e152.png)

Data-node config here: 
[data_node_config.txt](https://github.com/vegaprotocol/vega/files/11077328/data_node_config.txt)

# Observed behaviour

Data node is not able to start with visor

# Expected behaviour

Data node should be able to start

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by guoguojin** [comment]
There are a number of reasons this can happen:

1. The data-node has `NetworkHistory.WipeOnStartup = true`. This will cause data node to wipe any local network history it has stored locally before starting.
2. The data-node does not have any bootstrap peers defined in the configuration file, it therefore cannot retrieve any history information from peers.
3. The data-node does not have the correct ChainID in the configuration file. This causes the request to fail because the swarm key defaults to the ChainID if is empty in the configuration file, and thus has the wrong swarm key to fetch the network history data from peers.

**Comment by daniel1302** [comment]
More info is in thread here: https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1679771508378329

**Comment by guoguojin** [comment]
Another reason why fetching the network-history had failed for me in the past was because the peer-id I was using in the data-node configuration was not unique. i.e. I had copied the config from another machine and used the same peer id as one that already existed.

I don't think this is the reason for the error you're seeing in this instance, but it's something to bear in mind as a possible problem.
