### ISSUE TITLE
Unused network param in mainnet - reward.staking.delegation.payoutFraction

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8280]
The network param - `reward.staking.delegation.payoutFraction` seems to be unused and is available on mainnet

Its currently set to 1 in mainnet and I can’t find this param referenced anywhere in system tests or the specs.

https://explorer.vega.xyz/network-parameters

Please remove from mainnet genesis if this param is unused.

Reference Issue - https://github.com/vegaprotocol/specs/issues/1071

**Comment by wwestgarth** [comment]
I'm unsure of the intent of this ticket -- tts too late to remove the network parameters from the mainnet genesis file because mainnet is there now, and that is the genesis file.

Our unofficial deprecation path for network-parameters up until now have just been "they still exist, but do not do anything". I could remove them entirely from the code while being sure that the removal is handled properly across a protocol-upgrade. I think it would still class as a breaking change though because anyone using capsule (system-tests, mainnet-sim) etc would need to go and update their genesis files.

**Comment by wwestgarth** [comment]
I've changed my mind and we should do this more properly now we're in real-life-mainnet, and by that I mean:
- its still allowed to be set in the genesis file
- have it marked as deprecated in the code, and any proposals to change the value are rejected
- mark it as deprecated in the datanode and hide it from the list
- Add this change to the `deprecation` section of the changelog so people are aware and can act appropriately (update there capsule genesis files and whatever)
- The _following_ release we can remove it entirely as a breaking-change
