### ISSUE TITLE
network parameter not updating on mainnet after 0.71.5 patch release

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8400]
Some data nodes were able to get the updated net param during the upgrade. There are now a large number of data nodes that are not functional for mainnet.

Some validator nodes did not get the updated param. We need to either supply a command to get the data nodes back into the correct state or provide a patch fix.

**Comment by wwestgarth** [comment]
(I'm assuming here the network parameter in question is the one for the smart contracts).

This might not be a data node thing. When we load from a snapshot we turn off streaming any events to the datanode because they aren't "real" things that have happened on chain:
https://github.com/vegaprotocol/vega/blob/develop/core/processor/abci.go#L542

So when we loaded from the snapshot during the protocol-upgrade with the new network parameter, we simply didn't send the even to the data node which is why it doesn't know about it.
