### ISSUE TITLE
Data node network history segment hash divergence

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8401]
We have noticed that the SegmentId (i.e., segment hash) diverged on a pool of known data-node servers. I have gathered publically available data (see the process below) and concluded that it happened a couple of times:

1. at height `300` - we got 2 different segment ids, (the first segment)
2. at height `12900` - the number of different segment ids increased to 4 from 2,
3. at height `202500` - the number of different segment ids increased to 5 from 4,
4. at height `752100` - the number of different segment ids decreased to 4 from 5,
5. at height `988500` - the number of different segment ids increased to 8 from 4,
6. at height `1276300` - the number of different segment ids increased to 12 from 8 (first segment after Protocol Upgrade)

The detailed info can be found in the first comment

Note: all `height` references mean `toHeight` in a segment. i.e. `segment at height` means a segment that has `fromHeight = height - 299` and `toHeight = height`.

#### 1. I have gathered a list of publically known data-nodes:
- https://api0.vega.community
- https://api1.vega.community
- https://api2.vega.community
- https://vega-mainnet-data.commodum.io
- https://vega-query.mainnet.lovali.xyz
- https://vega-data.bharvest.io
- https://vega-data.nodes.guru:3008
- https://rest.velvet.tm.p2p.org
- https://vega-data-mainnet.rockrpc.net
- https://vega.greenfield.xyz
- https://vega.xprv.io/datanode
- https://vega.mainnet.stakingcabin.com
- https://vega-mainnet.anyvalid.com
- http://graphqlvega.gpvalidator.com:3008
- https://datanode.vega.pathrocknetwork.org
- https://vega.aurora-edge.com
- https://darling.network

#### 3. I have stored the results in the local Database into the table

```SQL
CREATE TABLE network_history_segments
(
  vega_time           TIMESTAMP WITH TIME ZONE NOT NULL,
  height              BIGINT                   NOT NULL,
  data_node           TEXT                     NOT NULL,
  segment_id          TEXT                     NOT NULL,
  PRIMARY KEY(vega_time, data_node)
);
```

#### 4. I queried it with the below

```SQL
WITH diff AS (
    SELECT height, COUNT(DISTINCT segment_id) AS count
    FROM network_history_segments
    GROUP BY height
    ORDER BY height
), diff_2 AS (
    SELECT
        height, 
        count,
        coalesce((LAG(count,1) OVER (
            ORDER BY height
        )), 0) AS previous_count
    FROM
        diff
)
SELECT s.height, d.previous_count, d.count, s.segment_id, s.data_node
FROM
	diff_2 d, network_history_segments s
WHERE 
    d.count <> d.previous_count
  AND
    s.height IN (d.height, d.height - 300)
ORDER BY s.height, s.segment_id;
```

**Comment by fkondej** [comment]
## Height 300

```
 height  | previous_count | count |                   segment_id                   |                 data_node                 
---------+----------------+-------+------------------------------------------------+-------------------------------------------
     300 |              0 |     2 | QmQNKi3gPrDZGn7GQECimvuM88LmZ5fVnjSyHbwRfpWWeX | https://api1.vega.community
     300 |              0 |     2 | QmQNKi3gPrDZGn7GQECimvuM88LmZ5fVnjSyHbwRfpWWeX | https://vega.aurora-edge.com
     300 |              0 |     2 | QmQNKi3gPrDZGn7GQECimvuM88LmZ5fVnjSyHbwRfpWWeX | https://api2.vega.community
     300 |              0 |     2 | QmQNKi3gPrDZGn7GQECimvuM88LmZ5fVnjSyHbwRfpWWeX | https://api0.vega.community
     300 |              0 |     2 | QmQNKi3gPrDZGn7GQECimvuM88LmZ5fVnjSyHbwRfpWWeX | https://vega.mainnet.stakingcabin.com
     300 |              0 |     2 | QmTo23Xg3L2PkPpSSrp8FSEqqASjXECbf512jnUzwjt4EK | https://darling.network

```

## Height 12600 (2 segment ids) -> 12900 (4 segment ids)

```
 height  | previous_count | count |                   segment_id                   |                 data_node                 
---------+----------------+-------+------------------------------------------------+-------------------------------------------
   12600 |              2 |     2 | QmU42pEkz5cpHarDmnUpFDLEwaPdTSukNQDnm3uNEmpaDD | https://vega.aurora-edge.com
   12600 |              2 |     2 | QmU42pEkz5cpHarDmnUpFDLEwaPdTSukNQDnm3uNEmpaDD | https://vega.mainnet.stakingcabin.com
   12600 |              2 |     2 | QmU42pEkz5cpHarDmnUpFDLEwaPdTSukNQDnm3uNEmpaDD | https://api2.vega.community
   12600 |              2 |     2 | QmU42pEkz5cpHarDmnUpFDLEwaPdTSukNQDnm3uNEmpaDD | https://api1.vega.community
   12600 |              2 |     2 | QmU42pEkz5cpHarDmnUpFDLEwaPdTSukNQDnm3uNEmpaDD | https://api0.vega.community
   12600 |              2 |     2 | QmbEKmwZwaYi6iusRRn2wW2HztiXKFyxgK6rCfRzmd3LBa | https://darling.network
   12900 |              2 |     4 | QmPETRkkLLGgMRsXL1UHWrXyXqx3oQWMDEwwSpPHBhphEi | https://api2.vega.community
   12900 |              2 |     4 | QmPETRkkLLGgMRsXL1UHWrXyXqx3oQWMDEwwSpPHBhphEi | https://api0.vega.community
   12900 |              2 |     4 | QmPETRkkLLGgMRsXL1UHWrXyXqx3oQWMDEwwSpPHBhphEi | https://api1.vega.community
   12900 |              2 |     4 | QmT4yMYBb2byuT2LeNdn775a9HguVAxs2CXKA3BigyVsaL | https://vega.aurora-edge.com
   12900 |              2 |     4 | QmZJTLgKLdyvinXvDkW3UjZDL9LCc5DCp1sdAoptJBU41v | https://darling.network
   12900 |              2 |     4 | QmbVWV9x5y9PVAiabh3ajBeEfUyGut9AEVP3rTM2gwM9wE | https://vega.mainnet.stakingcabin.com
```

### Height 202200 (4 segment ids) -> 202500 (5 segment ids)

```
 height  | previous_count | count |                   segment_id                   |                 data_node                 
---------+----------------+-------+------------------------------------------------+-------------------------------------------
  202200 |              4 |     4 | QmPKgg8FsbWsADvm1n9PE1B4fgumsdaGZ2VciAPsZ2sTGC | https://api1.vega.community
  202200 |              4 |     4 | QmPKgg8FsbWsADvm1n9PE1B4fgumsdaGZ2VciAPsZ2sTGC | https://api2.vega.community
  202200 |              4 |     4 | QmPKgg8FsbWsADvm1n9PE1B4fgumsdaGZ2VciAPsZ2sTGC | https://api0.vega.community
  202200 |              4 |     4 | QmSdRYEq9e4NdFg5u1NC1jgMJ8rrZ9f5LmNvhT6cvSrtXV | https://vega.aurora-edge.com
  202200 |              4 |     4 | QmUeNgM23KQcaVkv7pqbQeaXwSCattB6fYMRGu8brUMQcN | https://vega.mainnet.stakingcabin.com
  202200 |              4 |     4 | QmbZ6Gqf9v8TBmA31hvZBaUEg4enGAHkXa78MhsbK8sK4y | https://darling.network
  202500 |              4 |     5 | QmQcv4ZcSF46bm8iES87YUqxwnenKwRjY9a6hoiWyXwkxT | https://vega.mainnet.stakingcabin.com
  202500 |              4 |     5 | QmWXtiCDf9aAVZzjP6U6Y4Hjjt16DoKe5E71utCgZTHp5w | https://darling.network
  202500 |              4 |     5 | QmbSStu7oBSfwYCRqg212no6ApTWb8Zqqpq3eo5bwPrux9 | https://vega.aurora-edge.com
  202500 |              4 |     5 | QmeQFrH5JuzUrSNmpjE25djLnh1zkGZjWuxdfG8tGyifKu | https://api0.vega.community
  202500 |              4 |     5 | QmeQFrH5JuzUrSNmpjE25djLnh1zkGZjWuxdfG8tGyifKu | https://api2.vega.community
  202500 |              4 |     5 | QmeQFrH5JuzUrSNmpjE25djLnh1zkGZjWuxdfG8tGyifKu | https://api1.vega.community
  202500 |              4 |     5 | QmeUqeWTGQT41NzQf6tX4WHG9zzKscEGUPyV1YKRkECz2q | https://vega-data.nodes.guru:3008
```

**Comment by ettec** [comment]
I've cross checked all nodes where I can, there are some nodes configured without bootstrap peers which means its not possible to source the network history segment, and where the data differs it is only due to the delegations issue.

Where the data does not differ but we are seeing different segment ids, this is down to the validator enabling network history after block 0. 


Copying the below from slack regarding how to bring them back into line once the patch for the delegations bug is released:

FYI Been doing some investigation on how we can bring the datanodes with divergent history back into line once the patch to fix the non-deterministic delegations has been released.  Right now we have divergent node due to two scenarios (some investigation still to do on this - so can't rule out other causes quite yet):
Those who enabled network history after block 0.
Those impacted by the delegations bug.
The obvious, but heavyweight way, to bring these nodes back into line would be to unsafe_reset_all and play from block 0 or load from network history,  or in the case of scenario 2 roll it back to a height pre-divergence and do similar.  Not ideal.  Been doing some tests on an alternative simpler way which seems to work.  That is:
shutdown node and wait for at least 1 new segment to be created by the a node(s) we consider to have the correct state - the truth segment
Auto-initialise the node from the new truth segment as follows:
data-node node --auto-initialise=true --networkhistory.initialise.to-segment=<truth segment id> --networkhistory.initialise.block-count=<at least enough blocks to cover gap between truth segment and last processd block>

e.g:

data-node node --auto-initialise=true --networkhistory.initialise.to-segment=QmVhU5fzBaVCpoXP5UEYky4gmjm2r18TvpXeq1S9E86pqs --networkhistory.initialise.block-count=1000
This will resolve divergent nodes due to scenario 1, no downside.   For scenario 2 nodes, this will bring the network history and the delegations current state back into line, however they will still have very slight different delegation history - the seq nums, but we do not query this history in datanode so may be this is an acceptable solution?

**Comment by ettec** [comment]
Checks are complete - no other scenarios apart from the above 2 scenarios mentioned above where uncovered.
