### ISSUE TITLE
updateMarket after termination does not work

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega#8453]
## Description

As [this](https://github.com/vegaprotocol/frontend-monorepo/issues/4052) ticket described I tried to update settlement oracle for a terminated market. 
The update does not seem to go through

[This](https://governance.fairground.wtf/proposals/96028788e6ab80c85159f11db37799c698e9595c4ef98a101c0c173493be094d) market has been terminated and updated with [this](https://governance.fairground.wtf/proposals/7902d8e94664d4e62b743bfecba10d54556fdd89085ee744b08ab4ca4ce19ccb) proposal but the update does not seem to be reflected, on the market.
It seems to be stuck on the oracle settings where price needs to be greater than 0 and less than 0. 

## Steps to Reproduce

1. Create a market with a price filter that makes it so it cannot be settled,  and activate it
2. Terminate market
3. Propose an update to the market with a filter that makes it possible to settle the market
4. Settle market
5. Does not seem to take the updated value

## Expected behavior

Market updates, at least to oracle, after termination should be possible.

**Comment by wwestgarth** [comment]
> Note two impacts of this
> 
>     1. In the event a user lost access to the the pubkey they had supplied as the oracle they would be unable to ever settle the market ... not sure what happens in that scenario, sounds bad.
> 
>     2. We had planned to use this approach to provide a layer of protection against less well known oracles, so a user could hold a market update vote to change the oracle to one which has a known preconfigured value - effectively voting on settlement price. With this bug we cant do this so if someone creates a market with a niche oracle (for instance on the new WETH settlement asset) we have no way to mitigate the settlement risk.

FWIW the impact isn't this bad, updating terminated markets _in general_ does work. The issue was that the original market had a internal-timestamp for termination and because that wasn't updated from the original proposal it made it look like we were updating it to a value in the past which core didn't like (but is a bug).

If the market update to change the settlement oracles also updated the termination oracles to _anything else_ that wasn't an internal timestamp in the past (and it really doesn't matter what because its already terminated) it would have happily worked.
