### ISSUE TITLE
[Bug]: Parent market forgets successor market during checkpoint restart

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8855]
### Problem encountered

If you create a market and a successor market, then perform a checkpoint restart, the parent no longer lists the child as a successor post restart (although the child still lists the parent)

### Observed behaviour

        assert marketsTrading.get_market(child1.id)["parentMarketId"] == parent1.id
>       assert marketsTrading.get_market(parent1.id)["successorMarketId"] == child1.id
E       KeyError: 'successorMarketId'

tests/governance/test_markets.py:875: KeyError

### Expected behaviour

Parent and child remember each other.

### Steps to reproduce

```bash
1. Check out https://github.com/vegaprotocol/system-tests/tree/jake_successor_market_cont
2. pytest -k test_settled_markets_saved_in_checkpoint_for_time_window
```

### Software version

fef2b0d70bccde2bc695787f2fe27330472f1f2b

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/85151/

**Comment by EVODelavega** [comment]
This may be the expected behaviour. If the parent market has been settled and succeeded by this successor, then the parent no longer is part of the checkpoint. Referencing a parent market that, from the point of view of a checkpoint restart, never existed doesn't make much sense. The ELS will be restored from the checkpoint, so the data isn't lost, but on a checkpoint restart, any parent market ID would be referencing a non-existent market

**Comment by edd** [comment]
I also found this with GraphQL:

```
{
  parent: market(id: "d780eeb28a3a6e3a047019ca68e510dbe53f57b13eb33c9385221d128e218fce") {
    successorMarketID
  }
  marketsConnection(pagination: {last: 1}) {
    edges {
      node {
        id
        successorMarketID
        parentMarketID
      }
    }
  }
  successor: market(id: "749e5924010353243dc3423bf3bf7edcca312239d91a4bbe2e987646154470d0") {
    id
    parentMarketID
  }
}
```

```json
{
  "data": {
    "parent": {
      "successorMarketID": null
    },
    "marketsConnection": {
      "edges": [
        {
          "node": {
            "id": "4bd471659ae3e63e6671f10778c4cf801533b146dbb33c7aa3ab9ea90fd05320",
            "successorMarketID": "749e5924010353243dc3423bf3bf7edcca312239d91a4bbe2e987646154470d0",
            "parentMarketID": "d780eeb28a3a6e3a047019ca68e510dbe53f57b13eb33c9385221d128e218fce"
          }
        }
      ]
    },
    "successor": {
      "id": "749e5924010353243dc3423bf3bf7edcca312239d91a4bbe2e987646154470d0",
      "parentMarketID": "4bd471659ae3e63e6671f10778c4cf801533b146dbb33c7aa3ab9ea90fd05320"
    }
  }
}
```

**Comment by edd** [comment]
> The ELS will be restored from the checkpoint, so the data isn't lost, but on a checkpoint restart, any parent market ID would be referencing a non-existent market

Referencing a non-existent market would be better than no reference at all, IMO. That ID being populated is the only way that we could display that the market succeeded something else, so it could look like a display bug if we can't say that the market followed on from another.

**Comment by EVODelavega** [comment]
> That ID being populated is the only way that we could display that the market succeeded something else

I'm not sure if I entirely agree. The lineage missing the parent market is unavoidable: the checkpoint doesn't contain that market in any way shape or form, so we can at best include a parent market ID on the restored market. WRT the lineage API, having an entry for the restored market with an ID to a market record that doesn't exist may be an issue simply when it comes to the queries we run (selecting market data for records where parent market ID <> null, now having to account for that parent market ID potentially not being an existing market ID etc...). @guoguojin may know more about that.

The essence of it, in my view, is that the parent/successor lineage of course has to be preserved when we load a snapshot, but a checkpoint is just the minimum amount of data required to: preserve balances, active markets, and ELS. It's a potential starting point, rather than a continuation

**Comment by edd** [comment]
@EVODelavega I don't think the situation that you're describing lines up with what Jake is reporting. The parent market does still 'exist' in the data node, you can select it by ID and the datestamp/details of it. What is wrong is that it doesn't reference its successor, which definitely still exists. 

Either way, something about your answer feels off to me. I am not saying that every checkpoint has to contain the entire lineage, but that if an active market has a parent, the details of that parent should be correct.

**Comment by davidsiska-vega** [comment]
The lineage is expected to be known in the data node under normal circumstances. It would be nice if that could be true post LNL checkpoint restarts.

(recall @EVODelavega that you convinced me that I don't need to keep the list doubly linked in core and it's only needed in the data node)

**Comment by barnabee** [comment]
Markets need to reference their parents regardless of whether LNL restore has occurred. We can no longer accept nuking the data node DB and if we are keeping the market proposal it can’t selectively lose information.

**Comment by davidsiska-vega** [comment]
from Jake 
> the parent no longer lists the child as a successor post restart (although the child still lists the parent) 

and from Elias:
> Whatever data is restored from a checkpoint has already emitted events, so if the datanode didn't crash, and processed said events, then all relevant state should've been stored in the DB, but the core will not emit events for markets it didn't restore etc... it'll just restore the checkpoint and emit an event once a restored market, for example, leaves opening auction etc... what the datanode does in this case is not governed by checkpoints. In theory, it could just restore the data from before the checkpoint was restored, but if that's what we want to do, then arguably we should emit an event when we've loaded a checkpoint containing the restored markets (so the datanode knows that the other markets weren't restored) 

Makes it sound like we'd expect that post LNL checkpoint restart, when data node gets queried, both 
1.  parent lists the child as a successor and 
1. the child still lists the parent.

**Comment by EVODelavega** [comment]
OK, so I've made some changes for this. Assuming data-node has records for the parent market, the parent market ID will not be cleared if: The successor market had ELS state in the checkpoint (because this indicates the market left opening auction, and inherited state from the parent), or the parent market is included in the checkpoint.

The parent market will be cleared if the successor we're restoring never left opening auction when the checkpoint was created, and the parent market was not restored (ie the parent market has expired, and as such is not restored - the child doesn't succeed the parent, because the parent market never truly existed). This is all but impossible, though: the parent market would have to be extremely short-lived, somehow passed governance, never left opening auction, its successor should've passed governance, be in opening auction (which it also never leaves), a checkpoint is created and we wait the duration of the successor time window before restoring it.

For normal cases, this would either mean that a successor that previously left opening auction and inherited state keeps that state and the reference to the parent market, or both markets will be created as they normally would.

**Comment by jgsbennett** [comment]
Reopening per above comment

**Comment by EVODelavega** [comment]
yes, so the link doesn't exist yet when both are in opening auction because we only send the event when the successor market leaves opening auction. Core could emit an event when restoring a successor market that had already left opening auction before the checkpoint was taken, but that still won't update the data-node, as the trigger to create an entry in the lineage table only creates an entry if the successor market left opening auction:

```sql
IF OLD.trading_mode != 'TRADING_MODE_OPENING_AUCTION' OR NEW.trading_mode != 'TRADING_MODE_CONTINUOUS' THEN
    RETURN NULL;
END IF;
```

This is really a rather broad issue that I suspect will never have a perfect solution. When restoring a checkpoint, we can never be sure of what state the datanode DB will be in. It's possible for the datanode to have cleared the DB entirely, just as it's possible that since the checkpoint was created, more events were emitted, and the DB state is actually _"ahead"_ of the checkpoint state. Ideally, the datanode would be in the exact state that matches the state during which the checkpoint was created, but there's no way to verify this. The only real use-case of checkpoints would be disaster recovery, which means we will start with a number of markets in opening auction, and from that point things should run their regular course, which includes accounting for the fact that the successor market may not leave opening auction in the time window, and never trade from the restore point on, so I don't think we should attempt to send an event on restore.

**Comment by jgsbennett** [comment]
Closing again. Remaining bug is now described by:
https://github.com/vegaprotocol/vega/issues/8912
