### ISSUE TITLE
[GLS-064] DoS: Rate limits can be circumvented by providing a fictitious IP address in the X-Forwarded-For header.

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8979]
During a recent pen test audit it has been noted that it may be possible to bypass the data node rate limiting:

Rate-limiting can be circumvented by utilising the X-Forwarded-For header containing a fictitious IP address

Example:
`wfuzz -v -w wordlist/stage_routes.txt -w wordlist/loop_stage.txt -H "X-Forwarded-For: $randomIPaddress" -X GET  http://n05.stagnet1.vega.xyz:3008/api/v2/FUZZ?x=FUZ2Z`

Adding a customised X-Forwarded-For header to the request makes it possible to utilise a new token bucket on every request, thereby circumventing rate limiting.

This needs to be investigated to ensure that a DDOS attack cannot be taken on data nodes

**Comment by pscott31** [comment]
hmm, this header is important so that e.g. reverse proxies in front of the datanode can tell it where requests came from; I wonder if there is some secure way to know if a request came from a trusted proxy and only look at this header in that case. I can't imagine we are the first to encounter this conundrum, I'll  do a bit of reading

**Comment by gordsport** [comment]
Can we set a check that uses this only of its behind a proxy?
