### ISSUE TITLE
[Bug]: panic: unable to find signature

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#9113]
### Problem encountered

A new validator on the Mainnet network got a panic after restarting their node:

```log
2023-08-17T11:40:19.174+0200    PANIC   core.protocol.validators        validators/signatures.go:150    unable to find signature        {"error": "unable to find pending signature by ethereum address \"0xc4CfBAe580d452ABe563B5218cF454BeD9D5A67c\""} 
2023-08-17T11:40:19.174+0200    INFO    core.protocol   protocol/protocol.go:154        Stopping protocol services 
2023-08-17T11:40:19.174+0200    INFO    core.protocol.event-forwarder   evtforward/engine.go:153        Stopping the Ethereum Event Forwarder 
2023-08-17T11:40:19.174+0200    INFO    core.protocol.event-forwarder   evtforward/engine.go:156        The Event Forwarder engine stopped 
2023-08-17T11:40:19.174+0200    INFO    core.api.grpc   api/grpc.go:290 Gracefully stopping gRPC based API 
2023-08-17T11:40:19.174+0200    INFO    core.api.restproxy      rest/server.go:134      Stopping REST<>GRPC based API 
2023-08-17T11:40:19.174+0200    INFO    core.admin.validator-server     admin/server.go:154     Stopping Server<>RPC based API 
2023-08-17T11:40:19.723+0200    INFO    core    node/node.go:225        Vega shutdown complete  {"version": "v0.71.6", "version-hash": "7a23f5e2f0fb4981c8318253142e2e23e3aa4f7c"} 
panic: unable to find signature [recovered] 
        panic: unable to find signature 
goroutine 221 [running]: 
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1.1() 
        /home/runner/work/vega/vega/cmd/vega/commands/node/node.go:137 +0x59 
panic({0x2d3fc40, 0xc001ef21c0}) 
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x212 
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc00084c180?}) 
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65 
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000002000, {0xc005eba540, 0x1, 0x1}) 
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec 
go.uber.org/zap.(*Logger).Panic(0xc013834c60?, {0x35d3956?, 0x40?}, {0xc005eba540, 0x1, 0x1}) 
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59 
code.vegaprotocol.io/vega/core/validators.(*ERC20Signatures).offerValidatorAddedSignatures(0xc013834c60, {0xc00688f000?, 0xc00e0bbba0?}) 
        /home/runner/work/vega/vega/core/validators/signatures.go:150 +0x193 
code.vegaprotocol.io/vega/core/notary.(*SnapshotNotary).OfferSignatures(0x0?, 0x3, 0xc001283f90) 
        /home/runner/work/vega/vega/core/notary/snapshot.go:134 +0xbd 
code.vegaprotocol.io/vega/core/validators.(*ERC20Signatures).OfferSignatures(0xc013834c60) 
        /home/runner/work/vega/vega/core/validators/signatures.go:122 +0x6e 
code.vegaprotocol.io/vega/core/validators.(*Topology).BeginBlock(_, {_, _}, {{0xc002939be0, 0x20, 0x20}, {{0xb, 0x1}, {0xc000675398, 0x11}, ...}, ...}) 
        /home/runner/work/vega/vega/core/validators/topology.go:464 +0x370 
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc002939be0, 0x20, 0x20}, {{0xb, 0x1}, {0xc000675398, 0x11}, 0xa905ed, {0x2fd9f37, ...}, 
...}, ...}) 
        /home/runner/work/vega/vega/core/processor/abci.go:805 +0xeb5 
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc002939be0, 0x20, 0x20}, {{0xb, 0x1}, {0xc000675398, 0x11}, 0xa905ed, {0x2fd9f37, ...}, ...}, ...}) 
        /home/runner/work/vega/vega/core/blockchain/abci/abci.go:46 +0x75
```

### Observed behaviour

They `wanted to be sure we changed the ETH RPC and restarted vega visor and end up with following error`.

### Expected behaviour

the node should restart successfully.

### Steps to reproduce

```bash
It might not be easily reproducible.
```

### Software version

v0.71.6

### Configuration used

```shell
the Mainnet network.
```

**Comment by wwestgarth** [comment]
This bug affects a very specific code path. There was a point in main-net history when a validator was promoted and the `issueSignatures` command was used to generate signatures. The notary engine holds on to all the signature-aggregations that it started, and on snapshot restore will re-kick-off sending in signatures for those nodes *annouced, validator nodes* that haven't.

The problem is that the notary engine will kick-off new signatures for _all_ historic aggreations if the node hasn't sent them. For new nodes that have joined the network, this will be for all withdrawal etc. etc. that have every happened, which isn't great. For add/remove signatures specifically, the topology engine throws away the message-to-sign once it sees that the multisig contract has been updated, so when the notary engine tries to generate that signature we get a panic.

The fix is simple, so only add to the retry list if the signature aggregation is still pending.

*what is the impact?*
To be affected by this snapshot issue you must have:
- initiallly joined the network *after* the above signature generation for a node-leaving event
- announced yourself to the network and be in a pending/ersatz/tendermint state

If the above is true then _all_ subsequent attempts to snapshot restore will fail (including if a protocol upgrade occurs).

In terms of "why didn't testing catch it", the answer is mostly because of the node starting from a snapshot needing to be announced to the network -- our mainnet-snapshot-pipeline can't get into this state. It would be worth investigating if the new snapshot-compatibility pipeline could have picked it up. We could probably tweak the null-chain to get itself into the required state.
