### ISSUE TITLE
[Bug]: Inconsistent rejection reason for market param update

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9399]
### Problem encountered

Inconsistent rejection reason for the following market parameters for new market proposal 
**price_range**
if price range is 0 we get the wallet error
`"proposal_submission.terms.change.new_market.changes.sla_params.price_range (must be positive)"`

if price range is 101 we get the wallet error
`"proposal_submission.terms.change.new_market.changes.sla_params.price_range (must be at most 100)"`

**sla_competition_factor**
why is this a string when we are passing a number?
`TypeError: Cannot set vega.LiquiditySLAParameters.sla_competition_factor to 0: 0 has type <class 'int'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field LiquiditySLAParameters.sla_competition_factor`

Inconsistent rejection reason for market update proposal for parameter change with an invalid value

**market.liquidity.commitmentMinTimeFraction**
**market.liquidity.priceRange**
**market.liquidity.slaCompetitionFactor**
**market.liquidity.performanceHysteresisEpochs**

For all these parameters the rejection reason is `PROPOSAL_ERROR_MISSING_SLA_PARAMS` i would expect it to be `PROPOSAL_ERROR_INVALID_SLA_PARAMS`

In addition
**price_range**
update market proposal rejection - brackets should be consistent
`price range must be in range (0, 100]`

**sla_competition_factor**
why is this a string?
`TypeError: Cannot set vega.LiquiditySLAParameters.sla_competition_factor to 0: 0 has type <class 'int'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field LiquiditySLAParameters.sla_competition_factor`

### Observed behaviour

inconsistent error details/ rejection reason and value type string for an integer

### Expected behaviour

error details should be consistent
accurate rejection reason
when passing a number value, the type should be int

### Steps to reproduce

```bash
These tests have been setup with current behaviour which you can see in the system-test module `tests/governance/test_market_params.py` from branch `0044-LIME-083`

- test_boundary_price_range
- test_boundary_sla_competition_factor
- test_boundary_update_commitment_min_time_fraction
- test_boundary_update_price_range
- test_boundary_update_sla_competition_factor
- test_boundary_update_epoch_hysteresis
```

### Software version

dev branch

**Comment by gordsport** [comment]
As per [this bug](https://github.com/vegaprotocol/vega/issues/9049) the price range update market proposal rejection - brackets are correct.

**Comment by Sohill-Patel** [comment]
I took the comment to mean the rejection is expected and not the inconsistent brackets

**Comment by wwestgarth** [comment]
I think this was all fixed in: https://github.com/vegaprotocol/vega/pull/9375

The price range errors are now consistent and should return `price range must be strictly greater than 0 and less than or equal to 20`. The market update validation now matches the new market proposal validation so the market-change proposal shouldn't even get to the point where it would get rejected, it'll be rejected by the wallet first.

The reason why `sla_competition_factor` needs to be a string is because its a decimal value and we can't use float values in the protos. This is because the handling of floats are machine dependent. So in all cases where a decimal value is needed they go in (and come out) of core as a string and internally they are converted into a `num.Decimal()` which is architecture independent implementation of a decimal.

**Comment by EVODelavega** [comment]
Essentially what @wwestgarth said, but to address the `PROPOSAL_ERROR_MISSING_SLA_PARAMS` vs `PROPOSAL_ERROR_INVALID_SLA_PARAMS` part of the issue: we do return the correct errors as far as I can tell. The only reason why you'd see `PROPOSAL_ERROR_MISSING_SLA_PARAMS` is due to the SLA parameters not being set entirely, in which case the error is entirely accurate. Should this still be an issue if the SLA parameters are all correctly specified (bar one which is invalid), then please provide more details

**Comment by Sohill-Patel** [comment]
with the fix included in this pr https://github.com/vegaprotocol/vega/pull/9375 new market proposal or update market proposal for market params will return a wallet error. All errors are now uniform, closing issue
