### ISSUE TITLE
LP general account not updated with LP fees after network restart

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9415]
See test test_terminated_or_settled_market_before_checkpoint_is_not_resurrected
branch sla_rework_existing_1b

This AC
```

    Each market's aggregate LP fee accounts must be included in the checkpoint and where the network is restored, the
    aggregate LP fee account balance will be transferred to the LP's general account. (0044-LIME-034)
```

Fails in a test, after checkpoint restarted the LP fees in the market are not distributed to the SLA parties when the network is restarted. 

Before network is restarted I can see market level LP fees for distribution , only have 1 LP in market so they should receive 100% distribution.

SLA general account is updated with margin and bond balance but not LP fees.

**Comment by EVODelavega** [comment]
This seems to be related to the successor time window. Because the market is settled, the required market state is retained in the checkpoint, and the account balances are preserved, but the market itself isn't resurrected (to use the terms from the test). The fees will be distributed at the end of the successor time window, or when the market is succeeded.

**Comment by EVODelavega** [comment]
This is expected behaviour. Checkpoints do not retain state created by, or related to, ongoing trading on a market. Restoring from a checkpoint merely restores the markets from scratch, no positions, no orderbook, no trades, and thus no LP fees. The only thing that the checkpoint retains is ELS (because ELS is carried over from parent to successor markets). Any LP fees in market accounts will instead end up in a global account.
