### ISSUE TITLE
[Bug]: Vega network stops producing blocks

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#9674]
### Problem encountered

Vega network stops producing logs during one of the test subjobs, without any error or panic. Issue originally noticed in a test issue https://github.com/vegaprotocol/system-tests/issues/2581, which turned out to be because the network hangs. There is a [long thread on slack](https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1696434966337489) where we have so far attempted to rule out this being caused by the [system test memory usage](https://github.com/vegaprotocol/system-tests/issues/2828) (https://github.com/vegaprotocol/system-tests/pull/2928), but the problem still produces.

### Observed behaviour

Network stops producing logs during the test run.

### Expected behaviour

Network continues producing blocks

### Steps to reproduce

```bash
1. Run the "Nightly" test run.
2. Check the g-n subjob.
3. Check the vega node logs. Notice that the blocks just stop at the end for 2-3 minutes, before Jenkins kills all processes at the end of the job.
```

### Software version

4e8eddc12b13c7a551e03721689ed628e7ddbe83

### Jenkins run

https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests/detail/system-tests/4025/pipeline/41/

**Comment by wwestgarth** [comment]
There is definitely a bug here where the snapshot engine can lock up and freeze the network. I've marked the bug as low because it will only occur when there are a lot of markets on the network (more than we would even expect in real-life).

The problems seems to be with the size of the buffered channels we use, we set them up with 1000 workers:
```
treeKeysToSnapshotChan := make(chan treeKeyToSnapshot, numWorkers)
serializedStateChan := make(chan snapshotResult, numWorkers)
```

then push input into the "to snapshot" channel, and THEN read the results from the results channel:
```
for _, treeKeyToSnapshot := range treeKeysToSnapshot {
	treeKeysToSnapshotChan <- treeKeyToSnapshot
}

for res := range serializedStateChan {
    // STUFF
}
```

The thing is if `treeKeysToSnapshot >> numWorkers`, the workers will fill up the results-channels buffer, then all the workers will take more things to serialise and block when trying to add to the results-channel when it gets. They'll then stop reading from the input too-snapshot-channel which itself will fill up and we'll block here:
```
treeKeysToSnapshotChan <- treeKeyToSnapshot
```

and we lock up.

Dirty fix would be to increase the channel buffers to be `len(treeKeyToSnapshot)`, but I can't help feeling we should re-flow it a bit to avoid a design where it is possible to block like this.

**Comment by wwestgarth** [comment]
@jeremyletang had a great idea for when we get round to looking at this again properly, reducing the number of workers down to 1 (or very low) would show any issue straight away. Which would make it much easier to debug.

**Comment by jeremyletang** [comment]
We have increased the number of workers used to produce the snapshot, while the previous version was good enough for any real cases and would have cope with 200 markets, we should be able to do 10x that now. which will be more than enough for years on mainnet and good enough for the system-tests.
